version: '3.8'
 
services:
  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: nest-clean-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: