name: Run Unit Test

on:
  push:
    paths:
      - '3-implementando-o-solid/**'

jobs:
  run-unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Coloca o código do projeto no ambiente
      - uses: actions/checkout@v3
      # Instala o Node no ambiente
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      # Garante que o diretório correto seja usado para instalar as dependências
      - run: npm ci
        working-directory: ./3-implementando-o-solid
      # Executa os testes no diretório correto
      - run: npm run test
        working-directory: ./3-implementando-o-solid
      - run: ls -la ./3-implementando-o-solid

