@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-type: application/json

{
  "name": "felipy",
  "cpf": "12345678955",
  "address": "sera fina",
  "latitude": 12345,
  "longitude": 23312,
  "password": "adawdawdawd"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "cpf": "12345678955",
  "password": "adawdawdawd"
}

###

# @name create_recipient
POST {{baseUrl}}/recipients
Content-Type: applciation/json
Authorization: Bearer {{authToken}}