services:
  postgres:
    container_name: nest-clean-pg
    image: postgres:15
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: